# Similarity Between NumPy Arrays & Python List

## 1. Data Storage:
Both NumPy arrays and Python lists are used to store collections of data elements. They provide a way to organize and hold multiple values in a single structure. You can store various data types such as numbers, strings, or objects in both NumPy arrays and Python lists.

## 2. Indexing and Slicing: 
You can access individual elements of NumPy arrays and Python lists using indexing and slicing notation. Elements are accessed by their position in the array or list, starting from index 0.
Example as shown below:

In [24]:
# Below is the example of accessing individual element
import numpy as np

# Storing data elements in a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
print(f"This is the first element of the numpy_array = ",numpy_array[0])
# Storing data elements in a Python list
python_list = [1, 2, 3, 4, 5]
print(f"This is the first element of the puthon_ist = ",python_list[0])


This is the first element of the numpy_array =  1
This is the first element of the puthon_ist =  1


In [25]:
# Below are the example of slicing 
print(numpy_array[2:4])
print(python_list[2:4])

[3 4]
[3, 4]


## 3. Mutable: 
Both NumPy arrays and Python lists are mutable, meaning you can modify their elements after they are created. You can change the value of specific elements or add/remove elements from the array or list.

In [7]:
# Example of mutable in which we will change the first emement of both data type to 100
print("Data Before changing")
print(numpy_array)
print(python_list)
print("Data After changing")
numpy_array[0]=100
python_list[0]=100
print(numpy_array)
print(python_list)
# we are chaning again our data as previous for our next examples
numpy_array[0]=1
python_list[0]=1

Data Before changing
[100   2   3   4   5]
[100, 2, 3, 4, 5]
Data After changing
[100   2   3   4   5]
[100, 2, 3, 4, 5]


## 4. Iteration:
You can iterate over the elements of NumPy arrays and Python lists using loops (e.g., for loop) or other iteration mechanisms. This allows you to process each element sequentially

In [8]:
# Example on iterantions
print("Below is the result of iteration over numpy arrays")
for i in numpy_array:
    print(i)
print("Below is the result of iteration over python list")
for i in python_list:
    print(i)


Below is the result of iteration over numpy arrays
1
2
3
4
5
Below is the result of iteration over python list
1
2
3
4
5


## 5. Mathematical Operations:
Both NumPy arrays and Python lists support mathematical operations like addition, subtraction, multiplication, etc. However, NumPy arrays provide the advantage of performing these operations element-wise, making them more efficient for numerical computations.


In [23]:
# Below are the example of numpy array in which we perform additions.
numpy_array_added=numpy_array + 100
print(numpy_array_added)
# Below are the example of python array in which we perform additions.
# python_list_added=python_list + 100
# print(python_list_added)
# Please note that we can't add and multiple any integer to our list directly we can do the same by using loops

[101 102 103 104 105]


## 6. Mixed Data Types: 
Both NumPy arrays and Python lists can accommodate elements of different data types. They can store integers, floats, strings, and other Python objects.
But in numpy array we can only add a similar data type at a time. like we can store integer in out array so that each element of the array must be integer.

## 7. Dynamic Size:
Both NumPy arrays and Python lists can dynamically change in size. You can add or remove elements as needed, allowing for flexibility in managing the collection of data. 